server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zk
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/